---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-azresourcegraph
  annotations:
    # This tells crossplane beta render to connect to the function locally.
    #render.crossplane.io/runtime: Development
spec:
  package: xpkg.upbound.io/upbound/function-azresourcegraph:v0.8.0
